# Generated by Django 6.0.3 on 2026-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для чтения'),
        ),
    ]
