# Generated by Django 6.0.3 on 2026-04-13 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_read_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BookProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(help_text='Имя автора (если новый)', max_length=100)),
                ('new_genres', models.CharField(blank=True, help_text='Укажите новые жанры через запятую', max_length=255)),
                ('description', models.TextField()),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='proposals/')),
                ('read_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Причина отклонения (для уведомления)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Выберите существующего автора или оставьте пустым', null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
                ('genres', models.ManyToManyField(blank=True, help_text='Выберите жанры', to='books.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
