# Generated by Django 6.0.3 on 2026-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_read_link_bookproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproposal',
            name='author',
        ),
        migrations.AlterField(
            model_name='bookproposal',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookproposal',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.genre', verbose_name='Жанры (выберите из списка)'),
        ),
        migrations.AlterField(
            model_name='bookproposal',
            name='new_genres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Или укажите новые жанры через запятую'),
        ),
        migrations.AlterField(
            model_name='bookproposal',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
